### ISSUE TITLE
healthstone button not showing

### ISSUE THREAD

**Issue by cerka** [robert388/Necrosis-classic#18]
On french client, the button for healthstone is not showing up.
On english client, the button for healthstone is showing but does not work.

ps: tested on a lvl 11 demo

**Comment by froggiton** [comment]
On the german client the button for healstone is not showing too.

**Comment by cerka** [comment]
looks like the line https://github.com/robert388/Necrosis-classic/blob/4c1e31a254890a21c4c09504862f55dd389b29ee/Necrosis/Necrosis.lua#L2175
bug because it use non localized string `healthstone`
this bug may happend with the others one (`soulstone`, etc)

**Comment by cerka** [comment]
this PR should fix it
#26
but need some help for localization other than fr and en (see comments on PR #26)

**Comment by robert388** [comment]
Aye at this point localisation is not working. sry bout that..

**Comment by froggiton** [comment]
this bug still exists in the german version.
If i change the spell id in the spells.lua, then the button exists.

**Comment by Donlod** [comment]
Well for the german client, i think the problem is that the words in the string for stones is the other way round. In english its "create healthstone (lesser)" while in german its "healthstone create (lesser)".

So for the german client instead of
`spellName:find(self.Translation.Misc.Create .. " " .. self.Translation.Item.Healthstone)`

its the other way round
`spellName:find(self.Translation.Item.Healthstone .. " " .. self.Translation.Misc.Create`

The correct ranks for german client are as follows:
Necrosis.Translation.StoneRank = {
	["Minor"] = "schwach",
	["Major"] = "erheblich",
	["Lesser"] = "gering",
	["Greater"] = "gro\195\159"
}
